# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RCTGVRExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'GVRSDK'

  post_install do |installer|
      system(". ./pod_post_install.sh")
  end
end
